dist: xenial
sudo: required
services:
  - docker

script:
  - docker build -t komodo_docs_image .
  - docker run --rm -v $(pwd):/app/ -w /app/ -u $(id -u):$(id -g) komodo_docs_image
  - cd docs/.vuepress/dist/
  - echo 'developers.komodoplatform.com' > CNAME 

deploy:

-
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs/.vuepress/dist/
  repo: komodoplatform/developer-docs
  on:
    branch: master

# blocklist
branches:
  except:
  - gcharang

# safelist
branches:
  only:
  - master
